---
apiVersion: v1
kind: Pod
metadata:
 name: secondmultipod

spec:
 containers:
  - name: cont1
    image: nginx
    ports:
     - containerPort: 80
    imagePullPolicy: IfNotPresent

  - name: cont2
    image: k8s.gcr.io/fluentd-gcp:1.30
