apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: try11
  name: try11
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/try11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: try11
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: try11
    spec:
      containers:
      - image: 192.168.10.254:5000/simpleapp
        env:
        - name: ilike
          valueFrom:
           configMapKeyRef:
            name: colors
            key: favorite
        envFrom:
        - configMapRef:
           name: colors
        imagePullPolicy: Always
        name: simpleapp
        readinessProbe:
         exec:
          command:
           - cat 
           - /tmp/healthy
         periodSeconds: 5
        livenessProbe:
         exec:
          command:
           - cat 
           - /tmp/healthy
         periodSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
