---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: hostmyclaim

spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi

spec:
 containers:
  - name: cont1
    image: nginx
    ports:
     - containerPort: 80
    imagePullPolicy: IfNotPresent
    volumeMounts:
     - mountPath: /usr/share/nginx/html
       name: vol1
