---
apiVersion: v1
kind: Pod
metadata:
 name: firstpod
 labels:
  type: app1

spec:
 containers:
  - name: cont1
    image: nginx
    ports:
     - containerPort: 80
    imagePullPolicy: IfNotPresent
