apiVersion: v1
kind: Pod
metadata:
  name: test-pdfour
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache1
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  nodeName: station44.example.com
