apiVersion: v1
kind: Pod
metadata:
 name: webserver
 namespace: default
 labels:
  name: app1

spec:
 containers:
  - image: nginx
    name: cont1
    ports:
     - containerPort: 80
    imagePullPolicy: IfNotPresent

